######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 16 00:10:34 2010
######################################################################

TEMPLATE = lib
DESTDIR = ../bin
DEPENDPATH += .
INCLUDEPATH +=

QT      +=   core \
  sql 

# Input
HEADERS += profimaxrelationalmodel.h
SOURCES += profimaxrelationalmodel.cpp
