######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 11 16:35:46 2009
######################################################################

TEMPLATE = lib
DESTDIR = ../bin

DEPENDPATH += .
INCLUDEPATH +=  .

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

# Input
HEADERS += qcboxbutton.h
FORMS += qcboxbutton.ui
SOURCES += qcboxbutton.cpp
RESOURCES += qrc.qrc
