######################################################################
# Automatically generated by qmake (2.01a) ?? ???? 25 19:27:04 2009
######################################################################

TEMPLATE = lib
DESTDIR = ../bin
QT      +=   core \
  gui \
  sql \
  svg \
  xml \
  network \
  webkit \
  webkitwidgets
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += profimaxreport.h
FORMS += profimaxreport.ui
SOURCES += profimaxreport.cpp
