CREATE ROLE role_main
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE;

CREATE ROLE role_relcom
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE;

CREATE ROLE role_workflow
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE;